apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
spec:
  selector:
    matchLabels:
      app: webapp-mysql
  template:
    metadata:
      labels:
        app: webapp-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "webchat"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-mysql
spec:
  selector:
    app: webapp-mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: klysman08/imersao-gpt-webapp:v1
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          value: mysql://root:root@webapp-mysql:3306/webchat
        - name: NEXTAUTH_URL
          value: http://afe369ee18faa4c0f9cf4c005882668f-853924759.us-east-1.elb.amazonaws.com/api/auth
        - name: NEXTAUTH_SECRET
          value: "123456"
        - name: KEYCLOAK_CLIENT_ID
          value: gpt-webapp
        - name: KEYCLOAK_CLIENT_SECRET
          value: jMW0gepVafr0U4kzEap4c71tpLPS2BOd
        - name: KEYCLOAK_ISSUER
          value: http://a190e55e92b354214bbdde1a9a7e7ede-444134222.us-east-1.elb.amazonaws.com/realms/master
        - name: CHATSERVICE_URL
          value: "chatservice:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      #nodePort: 30000
      name: http