name: CI-CD
on: # Evento que vai disparar o workflow
  push: # Quando der push no repositório
    branches: ["main"] # Branches que vão disparar o workflow
  workflow_dispatch: # Quando clicar no botão de Run workflow

jobs:
  CI:
    runs-on: ubuntu-latest # Sistema operacional que vai rodar o job
    steps: # Passos que o job vai executar
      - uses: actions/checkout@v3 # Ação que vai fazer o checkout do repositório
      - name: Autenticando no Docker Registry # Nome do passo
        uses: docker/login-action@v2.2.0 # Ação que vai fazer o login no Docker Registry
        with: # Variáveis de ambiente
          username: ${{ secrets.DOCKERHUB_USR }} # Variável de ambiente que vai armazenar o usuário do Docker Registry
          password: ${{ secrets.DOCKERHUB_PWD }} # Variável de ambiente que vai armazenar a senha do Docker Registry
      - name: Docker build chatservice # Nome do passo
        uses: docker/build-push-action@v4.1.1 # Ação que vai fazer o build e push da imagem
        with: # Variáveis de ambiente
          context: ./chatservice # Diretório onde está o Dockerfile
          file: ./chatservice/Dockerfile # Caminho do Dockerfile
          push: true # Fazer push da imagem
          tags: | # Tags da imagem
            klysman08/imersao-chatservice:v${{ github.run_number }} 
            klysman08/imersao-chatservice:latest
      - name: Docker build webapp # Nome do passo
        uses: docker/build-push-action@v4.1.1 # Ação que vai fazer o build e push da imagem
        with:  # Variáveis de ambiente
          context: ./webapp # Diretório onde está o Dockerfile
          file: ./webapp/Dockerfile # Caminho do Dockerfile
          push: true # Fazer push da imagem
          tags: |
            klysman08/imersao-gpt-webapp:v${{ github.run_number }}
            klysman08/imersao-gpt-webapp:latest
