name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Autenticando no Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker build chatservice
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./chatservice
          file: ./chatservice/Dockerfile
          push: true
          tags: |
            klysman08/imersao-chatservice:v${{ github.run_number }}
            klysman08/imersao-chatservice:latest
      - name: Docker build webapp
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
            klysman08/imersao-gpt-webapp:v${{ github.run_number }}
            klysman08/imersao-gpt-webapp:latest
